/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentinelRouteImport } from './routes/sentinel'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as Day1RouteImport } from './routes/day1'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessRestrictedRouteImport } from './routes/access-restricted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as Day1IndexRouteImport } from './routes/day1.index'
import { Route as OpsTicketIdRouteImport } from './routes/ops.$ticketId'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as LabsSlugRouteImport } from './routes/labs.$slug'
import { Route as Day1HourRouteImport } from './routes/day1.$hour'
import { Route as AdminReviewRouteImport } from './routes/admin.review'

const SentinelRoute = SentinelRouteImport.update({
  id: '/sentinel',
  path: '/sentinel',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const Day1Route = Day1RouteImport.update({
  id: '/day1',
  path: '/day1',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRestrictedRoute = AccessRestrictedRouteImport.update({
  id: '/access-restricted',
  path: '/access-restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesRoute,
} as any)
const Day1IndexRoute = Day1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Day1Route,
} as any)
const OpsTicketIdRoute = OpsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => OpsRoute,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModulesRoute,
} as any)
const LabsSlugRoute = LabsSlugRouteImport.update({
  id: '/labs/$slug',
  path: '/labs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Day1HourRoute = Day1HourRouteImport.update({
  id: '/$hour',
  path: '/$hour',
  getParentRoute: () => Day1Route,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-restricted': typeof AccessRestrictedRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/day1': typeof Day1RouteWithChildren
  '/modules': typeof ModulesRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sentinel': typeof SentinelRoute
  '/admin/review': typeof AdminReviewRoute
  '/day1/$hour': typeof Day1HourRoute
  '/labs/$slug': typeof LabsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/ops/$ticketId': typeof OpsTicketIdRoute
  '/day1/': typeof Day1IndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/ops/': typeof OpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-restricted': typeof AccessRestrictedRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sentinel': typeof SentinelRoute
  '/admin/review': typeof AdminReviewRoute
  '/day1/$hour': typeof Day1HourRoute
  '/labs/$slug': typeof LabsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/ops/$ticketId': typeof OpsTicketIdRoute
  '/day1': typeof Day1IndexRoute
  '/modules': typeof ModulesIndexRoute
  '/ops': typeof OpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-restricted': typeof AccessRestrictedRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/day1': typeof Day1RouteWithChildren
  '/modules': typeof ModulesRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sentinel': typeof SentinelRoute
  '/admin/review': typeof AdminReviewRoute
  '/day1/$hour': typeof Day1HourRoute
  '/labs/$slug': typeof LabsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/ops/$ticketId': typeof OpsTicketIdRoute
  '/day1/': typeof Day1IndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/ops/': typeof OpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-restricted'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/day1'
    | '/modules'
    | '/ops'
    | '/reset-password'
    | '/sentinel'
    | '/admin/review'
    | '/day1/$hour'
    | '/labs/$slug'
    | '/modules/$slug'
    | '/ops/$ticketId'
    | '/day1/'
    | '/modules/'
    | '/ops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-restricted'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/sentinel'
    | '/admin/review'
    | '/day1/$hour'
    | '/labs/$slug'
    | '/modules/$slug'
    | '/ops/$ticketId'
    | '/day1'
    | '/modules'
    | '/ops'
  id:
    | '__root__'
    | '/'
    | '/access-restricted'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/day1'
    | '/modules'
    | '/ops'
    | '/reset-password'
    | '/sentinel'
    | '/admin/review'
    | '/day1/$hour'
    | '/labs/$slug'
    | '/modules/$slug'
    | '/ops/$ticketId'
    | '/day1/'
    | '/modules/'
    | '/ops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRestrictedRoute: typeof AccessRestrictedRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  Day1Route: typeof Day1RouteWithChildren
  ModulesRoute: typeof ModulesRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SentinelRoute: typeof SentinelRoute
  LabsSlugRoute: typeof LabsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentinel': {
      id: '/sentinel'
      path: '/sentinel'
      fullPath: '/sentinel'
      preLoaderRoute: typeof SentinelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day1': {
      id: '/day1'
      path: '/day1'
      fullPath: '/day1'
      preLoaderRoute: typeof Day1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-restricted': {
      id: '/access-restricted'
      path: '/access-restricted'
      fullPath: '/access-restricted'
      preLoaderRoute: typeof AccessRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/modules/': {
      id: '/modules/'
      path: '/'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/day1/': {
      id: '/day1/'
      path: '/'
      fullPath: '/day1/'
      preLoaderRoute: typeof Day1IndexRouteImport
      parentRoute: typeof Day1Route
    }
    '/ops/$ticketId': {
      id: '/ops/$ticketId'
      path: '/$ticketId'
      fullPath: '/ops/$ticketId'
      preLoaderRoute: typeof OpsTicketIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/labs/$slug': {
      id: '/labs/$slug'
      path: '/labs/$slug'
      fullPath: '/labs/$slug'
      preLoaderRoute: typeof LabsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day1/$hour': {
      id: '/day1/$hour'
      path: '/$hour'
      fullPath: '/day1/$hour'
      preLoaderRoute: typeof Day1HourRouteImport
      parentRoute: typeof Day1Route
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReviewRoute: typeof AdminReviewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReviewRoute: AdminReviewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface Day1RouteChildren {
  Day1HourRoute: typeof Day1HourRoute
  Day1IndexRoute: typeof Day1IndexRoute
}

const Day1RouteChildren: Day1RouteChildren = {
  Day1HourRoute: Day1HourRoute,
  Day1IndexRoute: Day1IndexRoute,
}

const Day1RouteWithChildren = Day1Route._addFileChildren(Day1RouteChildren)

interface ModulesRouteChildren {
  ModulesSlugRoute: typeof ModulesSlugRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesSlugRoute: ModulesSlugRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

interface OpsRouteChildren {
  OpsTicketIdRoute: typeof OpsTicketIdRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsTicketIdRoute: OpsTicketIdRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRestrictedRoute: AccessRestrictedRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  Day1Route: Day1RouteWithChildren,
  ModulesRoute: ModulesRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SentinelRoute: SentinelRoute,
  LabsSlugRoute: LabsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
