/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as LabsSlugRouteImport } from './routes/labs.$slug'

const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModulesRoute,
} as any)
const LabsSlugRoute = LabsSlugRouteImport.update({
  id: '/labs/$slug',
  path: '/labs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/modules': typeof ModulesRouteWithChildren
  '/labs/$slug': typeof LabsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/': typeof ModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/labs/$slug': typeof LabsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules': typeof ModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/modules': typeof ModulesRouteWithChildren
  '/labs/$slug': typeof LabsSlugRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/modules/': typeof ModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/modules'
    | '/labs/$slug'
    | '/modules/$slug'
    | '/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/labs/$slug'
    | '/modules/$slug'
    | '/modules'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/modules'
    | '/labs/$slug'
    | '/modules/$slug'
    | '/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  LabsSlugRoute: typeof LabsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/labs/$slug': {
      id: '/labs/$slug'
      path: '/labs/$slug'
      fullPath: '/labs/$slug'
      preLoaderRoute: typeof LabsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ModulesRouteChildren {
  ModulesSlugRoute: typeof ModulesSlugRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesSlugRoute: ModulesSlugRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ModulesRoute: ModulesRouteWithChildren,
  LabsSlugRoute: LabsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
